apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.version }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.version }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.version }}
  template:
    metadata:
      annotations:
       vpc-lattices-svcs.amazonaws.com/agent-inject: "true"
      labels:
        app: {{ .Release.Name }}-{{ .Values.version }}
    spec:
      containers:
      - name: {{ .Release.Name }}-{{ .Values.version }}
        image: public.ecr.aws/seb-demo/http-server:latest
        env:
        - name: PodName
          value: "Hello from {{ .Release.Name }}-{{ .Values.version }}"
        securityContext:
          runAsUser: 0
          runAsGroup: 1000  #different GID to prevent allow routing from iptable rule
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 15"]
      terminationGracePeriodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.version }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-{{ .Values.version }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
